### PR TITLE
Workaround for an S4 warnings bug.

### PR DESCRIPTION
**Pull request by pitakakariki**
A workaround to fix https://github.com/lme4/lme4/issues/331

### CODE REVIEW

**Comment by bbolker** [comment]
Thanks! Seems to have broken a travis check though.  I will have to see what's going on ...

**Comment by pitakakariki** [comment]
The errors have to do with `glmer.nb`. I don't think those tests are passing in the main branch either at the moment?

**Comment by bbolker** [comment]
I see your point, but as of the last Travis run it *was* working ...  I'll
try restarting the build and see if it fails this time ...

**Comment by pitakakariki** [comment]
Still passing then, that's pretty strange.

Slightly different environments for the two travis-ci checks, e.g. original has R 3.2.2, pull request has 3.2.3. I don't think it's the R version though, I've had `testthat::test_package("lme4")` fail with both 3.2.2 and in dev R on my laptop. (That's for "lme4/lme4", not "pitakakariki/lme4").

**Comment by bbolker** [comment]
I do know that the problems with `glmer.nb` are *very* sensitive.  It doesn't surprise me that the tests fail on another platform.  Hopefully I will find a day or two to dig into this in the very near future ...

**Comment by pitakakariki** [comment]
Looks like I've messed up this pull request by pushing additional commits to my fork. I'll close it and resubmit.

**Pull request closed without merging**
