### PR TITLE
control initial pass with nAGQ = 0

### PR DESCRIPTION
**Pull request by stevencarlislewalker**
A simple change to address #273.  To avoid argument creep, I put the change in `glmerControl`.  I used a pull request because I did this quickly and wanted to make sure other people would look at it.

### CODE REVIEW

**Comment by stevencarlislewalker** [comment]
TODO: documentation

**Comment by mmaechler** [comment]
Looks good to me...  but then I've never been an expert about the Hermite/Laplace/... approximation issues.  Maybe Rune.   OTOH, it's just an option and I like that you added it only to the control* argument list.

**Comment by bbolker** [comment]
fine with me ...

**Comment by runehaubo** [comment]
Looks good to me as well. If the `nAGQ=0` option has a tendency to underestimate the RE variance (this is my expectation based on similarity with h-likelihood methods, but I haven't got concrete evidence), it may generally in cases like this provide poor starting-values for these parameters, so a general way to by-pass the `nAGQ=0` initial step seems like a good idea.

**Comment by stevencarlislewalker** [comment]
Thanks @runehaubo.  You may add one more data point to your conjecture, as `nAGQ = 0` tends to underestimate the variance in this problem as well (issue #273).  It's helpful to hear that you have had similar experiences.

**Pull request merged**
