### PR TITLE
get weights from cbind response for in simulate.formula

### PR DESCRIPTION
**Pull request by pitakakariki**
A little bit messy but it gets the job done.

### CODE REVIEW

**Comment by pitakakariki** [comment]
This is for https://github.com/lme4/lme4/issues/400

**Comment by bbolker** [comment]
I hate to look a gift horse in the mouth, but ... could we have a couple lines of comments/documentation in the code about the logic used here? (Does this need any updates in the end-user documentation, or does it rather make the code do what the user would expect it to do in the first place?)

**Comment by bbolker** [comment]
OK, just *one* more: could you change `binWtsHack` to something more like `userWts` ?  Not that we don't have other ugly stuff in the code ... (`grep -i hack R/*.R` reveals `reFormHack` and `evalhack` variables as well as, of course, lots of comments ... maybe I'll try to fix those ...) I promise I'll take it then ...

**Comment by pitakakariki** [comment]
Ah, I saw `reFormHack` so I thought I was following naming convention!

I'm writing up some documentation for `?simulate.merMod`. New behaviour is what I would expect, but it can't hurt to tell people what we think it's meant to do.

**Comment by bbolker** [comment]
thanks!

**Pull request merged**
